#!/usr/local/bin/perl -w
# $Id: mksite,v 1.1 2004/07/23 20:10:22 cwest Exp $
use strict;

use lib qw[lib util/lib];
use PPT::Util;

clean_html_dir;

my @cmds = config_cmds;

foreach ( @cmds ) {
    copy_cmd_src     $_;
    copy_v7doc       $_;
    create_cmd_doc   $_;
    create_cmd_index $_;
}

generate_what;

generate_table;

generate_page('index.html');
generate_page('p5p-note.html');
generate_page('whence.html');
generate_page('who.html');
generate_page('why.html');
generate_page('poem.html');
