#!/bin/sh
( 
cat <<-'EOF';
	<TITLE>Unix Version 7 Commands</TITLE>
	<H1>Unix Version 7 Commands</H1>

	See <A HREF="http://cm.bell-labs.com/7thEdMan/index.html">Unix Seventh
	Edition Manual</A> for original <i>troff</i> source for this and more.

	<UL>
EOF

perl -00 -ne 'if (/^NAME\s*(\S+)\s+-\s*(\S.*)/m) { print qq(<LI><A HREF="$ARGV">$1</A> - $2\n) } ' * 

echo "</UL>"
) > index.html
