#!perl

=begin metadata

Name: program-example
Description: a demonstration of the PerlPowerTools common setup
Author: brian d foy, briandfoy@pobox.com
License: perl

=end metadata

=cut

package PerlPowerTools::program_example;
use PerlPowerTools::Modulino::Base;
our @ISA = qw(PerlPowerTools::Modulino::Base);

eval "no feature qw(module_true)" if $] > 5.39;

use strict;
use warnings;

=head1 NAME

program-example - a demonstration of the PerlPowerTools common setup

=head1 SYNOPSIS

	% perl -Ilib examples/program-example

=head1 DESCRIPTION

This module demonstrates using the L<PerlPowerTools::Modulino::Base> to handle
most of the application details, including the shims to handle special platform
considerations that we don't want to repeat in every program.

All of this would be fatpacked into a single file so the utility is still a
single-file drop in.

First, the C<options_spec> method is a L<Getopts::Long> specification. That
is all you need to do.

=cut

sub options_spec {
	return [qw(a=s b|boo c)];
	}

=pod

The C<main> does the actual work of the program, and returns the exit value
for the program.

L<PerlPowerTools::Modulino::Base> does the rest of the work to parse the
command line, handle input and output, and handle the orderly exit. See the
methods in that module to see what you have access to and what you might want
to override.

=cut

sub main {
	my( $self ) = @_;
	$self->output( "Hello there\n" );
	$self->error( $self->dumper($self->options) );
	$self->error( $self->dumper($self->arguments) );
	return $self->exit_code_success;
	}

no warnings;
__PACKAGE__;

