#!perl

=begin metadata

Name: program-example
Description: a demonstration of the PerlPowerTools common setup
Author: brian d foy, briandfoy@pobox.com
License: perl

=end metadata

=cut

package PerlPowerTools::program_example;
use PerlPowerTools::Modulino::Base;
our @ISA = qw(PerlPowerTools::Modulino::Base);

eval "no feature qw(module_true)" if $] > 5.39;

use strict;
use warnings;

=head1 NAME

program-example - a demonstration of the PerlPowerTools common setup

=head1 SYNOPSIS

	% perl -Ilib examples/program-example

=head1 DESCRIPTION

This module demonstrates using the L<PerlPowerTools::Modulino::Base> to handle
most of the application details, including the shims to handle special platform
considerations that we don't want to repeat in every program.

All of this would be fatpacked into a single file so the utility is still a
single-file drop in.

First, the C<options_spec> method is a L<Getopts::Long> specification. That
is all you need to do.

=cut

sub options_spec {
	return [qw(a=s b|boo c)];
	}

=pod

The C<program_coderef> returns an code reference that represents the main
program. It receives as arguments:

=over 4

=item * the package name of the class, which should be the package name for the
subclass representing this program

=item * a hash reference created by L<Getopts::Long> to represent the options

=item * an array ref of the remaining arguments that were not options, that have
globs expanded

=back

Inside the code ref, call C<output> for normal output that would normally go
to standard output, and C<error> for standard error. This allows tests to
override these.

Call the C<exit> method instead of C<exit> directly.

=cut

sub program_coderef {
	my $run_sub = sub {
		my( $class, $options, $arguments ) = @_;
		$class->output( "Hello there\n" );
		$class->error( $class->dumper($options) );
		$class->error( $class->dumper($arguments) );
		$class->exit(137);
		};
	}

# if we return without exiting, use that as the exit code
exit( __PACKAGE__->run ) unless caller;

no warnings;
__PACKAGE__;

