#!perl

package PerlPowerTools::rm;
use PerlPowerTools::Modulino::Base;
our @ISA = qw(PerlPowerTools::Modulino::Base);

eval "no feature qw(module_true)" if $] > 5.39;

use strict;
use warnings;

use File::Basename;
use File::Spec::Functions;
use Storable qw(dclone);

use constant EX_SUCCESS   => 0;
use constant EX_FAILURE   => 1;
use constant EX_USAGE     => 2;
use constant OP_SUCCEEDED => 0;
use constant OP_FAILED    => 1;

my $Program = basename($0);

=head1 NAME

rm - remove directory entries

=head1 SYNOPSIS

	% rm [-fiPrRv] file ...

=head1 DESCRIPTION

=cut

sub options_spec {
	return [qw(f i P r R v)];
	}

=pod

The C<program_coderef> returns an code reference that represents the main
program. It receives as arguments:

=over 4

=item * the package name of the class, which should be the package name for the
subclass representing this program

=item * a hash reference created by L<Getopts::Long> to represent the options

=item * an array ref of the remaining arguments that were not options, that have
globs expanded

=back

Inside the code ref, call C<output> for normal output that would normally go
to standard output, and C<error> for standard error. This allows tests to
override these.

Call the C<exit> method instead of C<exit> directly.

=cut

sub dumper { require Data::Dumper; Data::Dumper->new([@_])->Indent(1)->Sortkeys(1)->Terse(1)->Useqq(1)->Dump }

sub program_coderef {
	my $run_sub = sub {
		my( $class, $options, $arguments, $resolved_arguments, $raw_arguments ) = @_;

		my $self = $class->new(
			raw_arguments => $raw_arguments,
			options       => $options,
			files         => $arguments,
			);

		$self->postprocess_options;

		$self->error( "OPTIONS "  . dumper($options)            );
		$self->error( "ARGS "     . dumper($arguments)          );
		$self->error( "RESOLVED " . dumper($resolved_arguments) );
		$self->error( "RAW "      . dumper($raw_arguments)      );

		unless( () = $self->files ) {
			$self->exit(EX_SUCCESS) if $self->is_force;
			$self->error( "$Program: missing argument\n" );
			$self->usage;
			}

		my $errors = grep { $self->process_file( $_ ) } $self->files;
		$self->exit( $errors ? EX_FAILURE : EX_SUCCESS );
		};
	}


sub new {
	my( $class, %args ) = @_;
	bless \%args, $class;
	}

sub files {
	my $self = shift;
	$self->{'files'} = [] unless exists $self->{'files'};
	@{ $self->{files} }
	}

sub is_force       { $_[0]->options->{f} }
sub is_interactive { $_[0]->options->{i} }
sub is_overwrite   { $_[0]->options->{P} }
sub is_recursive   { $_[0]->options->{R} || $_[0]->options->{r} }
sub is_verbose     { $_[0]->options->{v} }

sub options { $_[0]->{options} }

sub postprocess_options {
	my( $self ) = @_;

	# this is rm particular processing: -f and -i turn off each
	# other, and the last one wins. Figure out which one is last
	# then filter out all earlier of the other.
	if( exists $self->options->{'f'} && exists $self->options->{'i'} ) {
		my $last;
		foreach ( reverse @{ $self->{raw_arguments} } ) {
			print STDERR "looking at <$_>\n";
			next unless /\A-[fi]\z/;
			$last = $_;
			last;
			}

		$self->options->{'i'} = undef if $last eq '-f';
		$self->options->{'f'} = undef if $last eq '-i';
		}

	return $self;
	}

sub process_file {
    my( $self, $filename ) = @_;

	my $method = do {
		if( -d $filename ) {
			if( ! $self->is_recursive ) {
				$self->error( "$Program: '$filename': is a directory\n" ) unless $self->is_force;
				return $self->is_force ? OP_SUCCEEDED : OP_FAILED;
			}
			'remove_directory';
		}
		else {
			'remove_file';
		}
	};

    my $result = $self->$method( $filename );
	return $self->is_force ? OP_SUCCEEDED : $result;
	}

sub remove_directory {
    my( $self, $dirname ) = @_;

    $self->output( "remove dir: $dirname");

	my $dh;
    unless( opendir( $dh, $dirname ) ) {
		$self->error( "$Program: cannot open '$dirname': $!\n" ) unless $self->is_force;
		return $self->is_force ? OP_SUCCEEDED : OP_FAILED;
    	}

    foreach my $file ( readdir($dh) ) {
		next if $file eq '.' || $file eq '..';
		my $path = catfile( $dirname, $file );

		my $method = -d $path ? 'remove_directory' : 'remove_file';
	    my $result = $self->$method($path);
    	}

    closedir $dh;

    unless( 1 || rmdir $dirname ) {
		$self->error( "$Program: cannot remove directory '$dirname': $!\n" ) unless $self->is_force;
		return $self->is_force ? OP_SUCCEEDED : OP_FAILED;
    	}

	$self->output( "$dirname\n" ) if $self->is_verbose;

    return OP_SUCCEEDED;
	}

sub remove_file {
    my( $self, $filename ) = @_;

    $self->output( "remove file: $filename\n");
    return;

	# Answering no to skip a file is not an error
    if( $self->is_interactive ) {
		$self->message( "$filename: ? " );
		return OP_SUCCEEDED if <STDIN> =~ /^[Nn]/;
    	}
    elsif( !$self->is_force && -e $filename && ! -w $filename ) {
		$self->message( "$filename: Read-only ? " );
		return OP_SUCCEEDED if <STDIN> =~ /^[Nn]/;
    	}

    unless( unlink $filename ) {
		$self->error( "$Program: cannot remove '$filename': $!\n" ) unless $self->is_force;
		return $self->is_force ? OP_SUCCEEDED : OP_FAILED;
    	}

	$self->output( "$filename\n" ) if $self->is_verbose;

    return OP_SUCCEEDED;
	}

# if we return without exiting, use that as the exit code
__PACKAGE__->run unless caller;

=head2 OPTIONS

=over 4

=item * -f - do not prompt the user for each file, and do not consider it an error if a file cannot be removed

=item * -i - prompt the user for each file.

=item * -P - a no-op, for compatibility. So implementations would overwrite files with random data

=item * -r - same as -R

=item * -R - remove directories recursively

=item * -v - show the name of each file after it is removed

=back

=head1 AUTHOR

Copyright (c) brian d foy, bdfoy@cpan.org

The original version of this program was written by Steve Kemp,
steve@steve.org.uk, but almost none of that remains.

=head1 LICENCE

This program is licensed under the Artistic License 2.0.

=cut

no warnings;
__PACKAGE__;

