#!perl

package PerlPowerTools::rm;
use PerlPowerTools::Modulino::Base;
our @ISA = qw(PerlPowerTools::Modulino::Base);

eval "no feature qw(module_true)" if $] > 5.39;

use strict;
use warnings;

use File::Basename;
use File::Spec::Functions;

use constant OP_SUCCEEDED => 0;
use constant OP_FAILED    => 1;

=begin metadata

Name: rm
Description: remove directory entries
Author: brian d foy, briandfoy@pobox.com
License: perl

=end metadata

=cut

=head1 NAME

rm - remove directory entries

=head1 SYNOPSIS

	% rm [-fiPrRv] file ...

=head1 DESCRIPTION

The B<rm> program removes the files or directories specified as arguments.

=cut

sub options_spec {
	return [qw(f i P r R v)];
	}

sub main {
	my( $self ) = @_;

	unless( () = $self->files ) {
		return $self->exit_code_success if $self->is_force;
		$self->error( $self->program_name . ": missing argument\n" );
		$self->usage;
		}

	my $errors = grep { $self->process_file( $_ ) == OP_FAILED } $self->files;

	return $errors ? $self->exit_code_failure : $self->exit_code_success;
	}

sub files {
	@{ $_[0]->{'arguments'} }
	}

sub is_force       { $_[0]->options->{f} }
sub is_interactive { $_[0]->options->{i} }
sub is_overwrite   { $_[0]->options->{P} }
sub is_recursive   { $_[0]->options->{R} || $_[0]->options->{r} }
sub is_verbose     { $_[0]->options->{v} }

sub postprocess_options {
	my( $self ) = @_;

	# this is rm particular processing: -f and -i turn off each
	# other, and the last one wins. Figure out which one is last
	# then filter out all earlier of the other.
	if( $self->is_force && $self->is_interactive ) {
		my $last = '';

		my @argv;
		foreach ( @{ $self->command_line } ) {
			last if /\A--\z/;
			s/\A-//;
			push @argv, map { "-$_" } split //, $_;
			}

		foreach ( reverse @argv ) {
			next unless /\A-[fi]\z/;
			$last = $_;
			last;
			}

		$self->options->{'i'} = undef if $last eq '-f';
		$self->options->{'f'} = 1     if $last eq '-f';

		$self->options->{'i'} = 1     if $last eq '-i';
		$self->options->{'f'} = undef if $last eq '-i';
		}

	$self->error( "-P ignored" ) if $self->is_overwrite;

	return $self;
	}

sub process_file {
    my( $self, $filename ) = @_;

	my $method = do {
		if( -d $filename ) {
			if( ! $self->is_recursive ) {
				$self->error( $self->program_name . ": '$filename': is a directory\n" ) unless $self->is_force;
				return $self->is_force ? OP_SUCCEEDED : OP_FAILED;
			}
			'remove_directory';
		}
		else {
			'remove_file';
		}
	};

    my $result = $self->$method( $filename );
	return $self->is_force ? OP_SUCCEEDED : $result;
	}

sub remove_directory {
    my( $self, $dirname ) = @_;

	my $dh;
    unless( opendir( $dh, $dirname ) ) {
		$self->error( $self->program_name . ": cannot open '$dirname': $!\n" ) unless $self->is_force;
		return $self->is_force ? OP_SUCCEEDED : OP_FAILED;
    	}

    foreach my $file ( readdir($dh) ) {
		next if $file eq '.' || $file eq '..';
		my $path = catfile( $dirname, $file );

		my $method = -d $path ? 'remove_directory' : 'remove_file';
	    my $result = $self->$method($path);
    	}

    closedir $dh;

    unless( 1 || rmdir $dirname ) {
		$self->error( $self->program_name . ": cannot remove directory '$dirname': $!\n" ) unless $self->is_force;
		return $self->is_force ? OP_SUCCEEDED : OP_FAILED;
    	}

	$self->output( "$dirname\n" ) if $self->is_verbose;

    return OP_SUCCEEDED;
	}

sub remove_file {
    my( $self, $filename ) = @_;

	# Answering no to skip a file is not an error
    if( $self->is_interactive ) {
		$self->output( "$filename: ? " );
		return OP_SUCCEEDED if $self->single_line_input =~ /^[Nn]/;
    	}
    elsif( !$self->is_force && -e $filename && ! -w $filename ) {
		$self->ouput( "$filename: Read-only ? " );
		return OP_SUCCEEDED if $self->single_line_input =~ /^[Nn]/;
    	}

	unless( -e $filename ) {
		$self->error( $self->program_name . ": cannot remove '$filename': No such file or directory\n" ) unless $self->is_force;
		return $self->is_force ? OP_SUCCEEDED : OP_FAILED;
		}

    unless( unlink $filename ) {
		$self->error( $self->program_name . ": cannot remove '$filename': $!\n" ) unless $self->is_force;
		return $self->is_force ? OP_SUCCEEDED : OP_FAILED;
    	}

	$self->output( "$filename\n" ) if $self->is_verbose;

    return OP_SUCCEEDED;
	}

# if we return without exiting, use that as the exit code
__PACKAGE__->run unless caller;

=head2 OPTIONS

=over 4

=item * -f - do not prompt the user for each file, and do not consider it an error if a file cannot be removed

=item * -i - prompt the user for each file.

=item * -P - a no-op, for compatibility. Some implementations would overwrite files with random data

=item * -r - same as -R

=item * -R - remove directories recursively

=item * -v - show the name of each file after it is removed

=back

=head1 AUTHOR

Copyright (c) 2023-2026 brian d foy, briandfoy@pobox.com

The original version of this program was written by Steve Kemp,
steve@steve.org.uk, but almost none of that remains.

=head1 LICENCE

This program is licensed under the Artistic License 2.0.

=cut

no warnings;
__PACKAGE__;

