name: "Closed Pull Request Labeler"
on:
    pull_request_target:
        types:
            - closed

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  merged:
    if: github.event.pull_request.merged == true
    environment: housekeeping
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        perl .github/bin/labeler ${{ github.event.number }} remove
        perl .github/bin/labeler ${{ github.event.number }} add 'Status: accepted'
  rejected:
    if: github.event.pull_request.merged == false
    environment: housekeeping
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        perl .github/bin/labeler ${{ github.event.number }} remove
        perl .github/bin/labeler ${{ github.event.number }} add 'Status: rejected'
