# This action requires a personal access token with issues and pull requests
# read-write permissions. The GITHUB_TOKEN that the action supplies only
# has read permissions since the merge is coming from a fork (usually).
name: merge-labeler

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
on:
  pull_request:
    types:
      - closed

jobs:
  relabel:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: merge
    steps:
    - uses: actions/checkout@v3
    - env:
        MERGE_TOKEN: ${{ secrets.MERGE_TOKEN }}
      run: |
        perl util/merge-labeler  ${{ github.repository }} ${{ github.event.number }}

