name: "Pull Request Labeler"
on:
    pull_request_target:
        types:
            - closed

jobs:
  rejected:
    if: github.event.pull_request.merged == false
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


  merge:
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://github.com/actions-ecosystem/action-remove-labels
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            'Priority: critical'
            'Priority: high'
            'Priority: low'
            'Priority: backlog'
            'Status: awaiting cpan testers'
            'Status: can't reproduce'
            'Status: changes requested'
            'Status: needs details'
            'Status: needs feedback'
            'Status: needs help'
            'Status: needs testing'
            'Status: needs verification'
            'Status: stalled'
            'Status: verified'

